# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) Copyright 2025 Andrew Bower <andrew@bower.uk>

stages:
  - build

before_script:
  - apt-get update && apt-get -y install libcap-dev

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
