.Dd January 4, 2025.
.Dt xchpst 8
.Os
.Sh NAME
.Nm xchpst.fake
.Nd fake xchpst that passes compatible arguments to chpst
.Sh SYNOPSIS
.Nm
.Op Ar XCHPST-OPTIONS
.Fl @
.Op Ar CHPST-OPTIONS
.Op Fl -
.Op Ar COMMAND ...
.Sh DESCRIPTION
.Pp
The
.Nm
script strips all options preceding the
.Fl @
separator
and passes the remainder of the arguments to
.Xr chpst 8 .
.Pp
The purpose of this script is to allow runscripts to take advantage of
.Nm xchpst Ns 's
advanced hardening features when the 'xchpst' package is installed and
fall back to only the classical
.Nm chpst
features otherwise, without having to have conditionality in the
runscripts which might reduce their readability.
.Pp
To be useful,
.Nm
should be installed as
.Pa /usr/bin/xchpst .
.Sh EXIT STATUS
The exit status is the return code from
.Nm chpst
or the target command.
.Sh EXAMPLES
The following command,
.Dl exec xchpst --cap-bs-keep CAP_SYS_TIME -@ -p 4 -- myntpd -D
in the absence of the real
.Nm xchpst
tool, is equivalent to:
.Dl exec chpst -p 4 -- myntpd -D
.Sh AUTHORS
.An -nosplit
.An Andrew Bower Aq Mt andrew@bower.uk
.Sh BUGS
Please raise bug reports at:
.Lk https://gitlab.com/abower/xchpst/-/issues
